[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
artmural = "Hk2AAbbrrjJFH4Wkm3DsudgGSWp2ftgL97dzfgxUkkzq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/preyanshu/test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/home/preyanshu/helo_3/artifacts/arcium_program_0.3.0.so"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/home/preyanshu/multipartycomputation_arcium/artifacts/arcium_program_0.3.0.so"
